# Module 4 - Lab Exercises

In [1]:
# Create a pandas Series from a list of random integers and 
# display its first three elements.
import pandas as pd
data = {
"Column A": [1,2,3],
"Column B": [4,5,6],
"Column C": [7,8,9]
}
df = pd.DataFrame(data)
df.head(2)

   Column A  Column B  Column C
0         1         4         7
1         2         5         8

In [2]:
# Create a Series with custom index labels and retrieve the element at index label 'b'.(📙Page 124)
import pandas as pd
s = pd.Series([10,20,30], index =["a", "b","c"])
value = s.loc["b"]
value

np.int64(20)

In [3]:
# Create a Series from a dictionary and check if a specific key exists in it. (📙Page 126)
# Run the check once to return True and once to return False
import pandas as pd
data = {
    "a": 100,
    "b": 200,
    "c": 300
}
s = pd.Series(data)

In [4]:
# Perform element-wise operations on the Series you just created: multiply all values by 2.(📙Page )
import pandas as pd
data = {
    "a": 100,
    "b": 200,
    "c": 300
}
s = pd.Series(data)
s * 2

a    200
b    400
c    600
dtype: int64

In [5]:
# Create a Series with some missing values (use np.nan) and check for missing values using isna().(📙Page )
import pandas as pd
import numpy as np
s=pd.Series([1, 2, np.nan, 4, np.nan, 6])
print(s)
print("\nMissing values (isna()):")
print(s.isna())

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
5    6.0
dtype: float64

Missing values (isna()):
0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [6]:
# Fill missing values in the Series with the mean of the non-missing values.(📙Page )
s=pd.Series([1, 2, np.nan, 4, np.nan, 6])
print("\nAfter filling values with mean:")
print(s.fillna(s.mean()))

After filling values with mean:
0    1.00
1    2.00
2    3.25
3    4.00
4    3.25
5    6.00
dtype: float64

In [7]:
# Create a 3x3 DataFrame from a dictionary of lists and display its first two rows.(📙Page )
# The columns should be named: A, B, and C
import pandas as pd
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
})
print("\nFirst two rows:")
print(df.head(2))

First two rows:
   A  B  C
0  1  4  7
1  2  5  8

In [8]:
# Add a new column to the DataFrame you just created (📙Page )
# where each value is the sum of two existing columns.
df['D'] = df["A"] + df["B"]
print(df)

   A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9

In [9]:
print(df)
print("\nRow at index 1:")
print(df.loc[1])

   A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9

Row at index 1:
A    2
B    5
C    8
D    7
Name: 1, dtype: int64

In [10]:
# Select only specific columns from the DataFrame you created.(📙Page )
print(df)
print("\nSelected columns A and C:")
print(df[["A", "C"]])

   A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9

Selected columns A and C:
   A  C
0  1  7
1  2  8
2  3  9

In [11]:
# Drop a column from the DataFrame and display the updated DataFrame.(📙Page 141)
print (df)
print("\nAfter dropping column B:")
print(df.drop("B", axis=1))

   A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9

After dropping column B:
   A  C  D
0  1  7  5
1  2  8  7
2  3  9  9

In [12]:
# Change the index of of the DataFrame you created
# to a custom index and display it.(📙Page 128)
print(df)
df.index = ["X", "Y", "Z"]
print("\nAfter changing index:")
print(df)

   A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9

After changing index:
   A  B  C  D
X  1  4  7  5
Y  2  5  8  7
Z  3  6  9  9

In [13]:
# Use iloc to select the second row of the DataFrame.(📙Page 147)
print(df)
print("\nSecond row:")
print(df.iloc[1])

   A  B  C  D
X  1  4  7  5
Y  2  5  8  7
Z  3  6  9  9

Second row:
A    2
B    5
C    8
D    7
Name: Y, dtype: int64

In [14]:
# Use loc to select all rows where column 'A' is greater than 1.(📙Page 148)
print(df)
print("\nColumn A is greater than 1:")
print(df.loc[df["A"] > 1])

   A  B  C  D
X  1  4  7  5
Y  2  5  8  7
Z  3  6  9  9

Column A is greater than 1:
   A  B  C  D
Y  2  5  8  7
Z  3  6  9  9

In [15]:
# Select rows where values in column 'C' are even.(📙Page )
import pandas as pd
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
})
print(df)
print("\nRows where C is even:")
print(df.loc[df["C"] % 2 == 0])

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

Rows where C is even:
   A  B  C
1  2  5  8

In [16]:
# Use a Boolean mask to select rows where column 'A' is greater than 1 and column 'C' is less than 9.(📙Page 148)
import pandas as pd
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
})
print(df)
print("\nBoolean mask:")
mask = (df["A"] > 1) & (df["C"] < 9)
print(df[mask])

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

Boolean mask:
   A  B  C
1  2  5  8

In [17]:
# Sort a DataFrame by column 'A' in descending order.(📙Page 160-161)
import pandas as pd
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
})
print(df)

print("\n Ascending order:")
print(df.sort_values("A", ascending=False))

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

 Ascending order:
   A  B  C
2  3  6  9
1  2  5  8
0  1  4  7

In [18]:
# Rank values in column 'C'.(📙Page )
print("\nRanks of column C:")
print(df['C'].rank())

Ranks of column C:
0    1.0
1    2.0
2    3.0
Name: C, dtype: float64

In [19]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}, index=[0, 1, 2])
print(df.reindex([0, 1, 2, 3, 4]))

     A    B    C
0  1.0  4.0  7.0
1  2.0  5.0  8.0
2  3.0  6.0  9.0
3  NaN  NaN  NaN
4  NaN  NaN  NaN

In [20]:
# Forward fill missing values in the reindexed DataFrame.(📙Page )
Hurt = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}, index=[0, 1, 2])
Hurt_reindexed = df.reindex([0, 1, 2, 3, 4,])
print("\nHurt_reindexed:")
print(Hurt_reindexed.ffill())

Hurt_reindexed:
     A    B    C
0  1.0  4.0  7.0
1  2.0  5.0  8.0
2  3.0  6.0  9.0
3  3.0  6.0  9.0
4  3.0  6.0  9.0

In [21]:
# Create another DataFrame and perform element-wise addition.(📙Page )
Paint_it_black_dataframe = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60],
    'C': [70, 80, 90]
})
print("\nPaint it black dataframe:")
print(Paint_it_black_dataframe)

print("\nKasmir dataframe:")
Kashmir_dataframe = pd.DataFrame({
    'A': [32, 29, 39],
    'B': [490, 507, 601],
    'C': [73, 81, 90]
})
print(Kashmir_dataframe)
print("\nPaint it black dataframe + Kashmir dataframe:")
print(Paint_it_black_dataframe + Kashmir_dataframe)

Paint it black dataframe:
    A   B   C
0  10  40  70
1  20  50  80
2  30  60  90

Kasmir dataframe:
    A    B   C
0  32  490  73
1  29  507  81
2  39  601  90

Paint it black dataframe + Kashmir dataframe:
    A    B    C
0  42  530  143
1  49  557  161
2  69  661  180

In [22]:
# Perform element-wise multiplication between two DataFrames.(📙Page )
Paint_it_black_dataframe
Kashmir_dataframe
print("\nPaint it black dataframe * Kashmir dataframe:")
print(Paint_it_black_dataframe * Kashmir_dataframe)

Paint it black dataframe * Kashmir dataframe:
      A      B     C
0   320  19600  5110
1   580  25350  6480
2  1170  36060  8100

In [23]:
# Use add() with a fill value to handle missing values in arithmetic operations. (📙Page 155)
from pandas import Series, DataFrame

Paint_it_black_dataframe = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60],
    'C': [70, 80, 90]
})

Rain_song = pd.DataFrame({
    "W": [323, 580, 333, 491],  
    "X": [268, 919, 812, 370],
    "Y": [750, 612, 983, 965],
    "Z": [776, 611, 956, 939]
})
Rain_song.add(Paint_it_black_dataframe, fill_value=0)

      A     B     C      W      X      Y      Z
0  10.0  40.0  70.0  323.0  268.0  750.0  776.0
1  20.0  50.0  80.0  580.0  919.0  612.0  611.0
2  30.0  60.0  90.0  333.0  812.0  983.0  956.0
3   NaN   NaN   NaN  491.0  370.0  965.0  939.0

In [34]:
# Apply a function to square all elements in column 'A'.(📙Page 107)
Paint_it_black_dataframe['A'] = Paint_it_black_dataframe['A'].apply(np.square)
print(Paint_it_black_dataframe)

              A   B         C
0     100000000  40  8.366600
1   25600000000  50  8.944272
2  656100000000  60  9.486833

In [30]:
# Apply the NumPy square root function to column 'C'.(📙Page 107)
Paint_it_black_dataframe = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60],
    'C': [70, 80, 90]
})
Paint_it_black_dataframe['C'] = Paint_it_black_dataframe['C'].apply(np.sqrt)
print(Paint_it_black_dataframe)

    A   B         C
0  10  40  8.366600
1  20  50  8.944272
2  30  60  9.486833

In [40]:
# Define a custom function and apply it to a column.(📙Page )
df = pd.DataFrame({'scores': [85, 92, 78, 60, 95]})
def grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    else:
        return 'F'
df['grade'] = df['scores'].apply(grade)
graded_df = df
print(graded_df)

   scores grade
0      85     B
1      92     A
2      78     C
3      60     F
4      95     A

In [45]:
# Create a new categorical column and group the DataFrame by this column.(📙Page )
import pandas as pd

df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60],
    'C': [70, 80, 90]
})

def categorize_B(x):
    if x >= 55:
        return 'High'
    elif x >= 45:
        return 'Medium'
    else:
        return 'Low'

gimme_shelter = df.copy()
gimme_shelter["B_category"] = gimme_shelter["B"].apply(categorize_B)

print(gimme_shelter)

    A   B   C B_category
0  10  40  70        Low
1  20  50  80     Medium
2  30  60  90       High

In [46]:
# Compute the sum of column 'A' for each group.(📙Page )
gimme_shelter
print(gimme_shelter.groupby("B_category")["A"].mean())

B_category
High      30.0
Low       10.0
Medium    20.0
Name: A, dtype: float64

In [49]:
# Reshape a DataFrame from long to wide format using pivot.(📙Page 277)
import pandas as pd

df_long = pd.DataFrame({
    'name':     ['Alice', 'Alice', 'Bob', 'Bob'],
    'subject':  ['Math', 'Science', 'Math', 'Science'],
    'score':    [85, 92, 78, 88]
})

df_wide = df_long.pivot(index='name', columns='subject', values='score').reset_index()
df_wide.columns.name = None

print(df_long)
print()
print(df_wide)

    name  subject  score
0  Alice     Math     85
1  Alice  Science     92
2    Bob     Math     78
3    Bob  Science     88

    name  Math  Science
0  Alice    85       92
1    Bob    78       88

In [50]:
# Melt a wide DataFrame back into long format.(📙Page 277)
import pandas as pd

df_long = pd.DataFrame({
    'name':     ['Alice', 'Alice', 'Bob', 'Bob'],
    'subject':  ['Math', 'Science', 'Math', 'Science'],
    'score':    [85, 92, 78, 88]
})

df_wide = df_long.pivot(index='name', columns='subject', values='score').reset_index()
df_wide.columns.name = None

df_melted = df_wide.melt(id_vars='name', var_name='subject', value_name='score')

print(df_wide)
print()
print(df_melted)

    name  Math  Science
0  Alice    85       92
1    Bob    78       88

    name  subject  score
0  Alice     Math     85
1    Bob     Math     78
2  Alice  Science     92
3    Bob  Science     88